### ISSUE TITLE
Impossible to activate 

### ISSUE THREAD

**Issue by bugsysop** [youknowriad/averroes#3]
**Error message:**

````
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Sg (http://localhost/gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:142:327)
    at m (http://localhost/gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:12:388)
    at ed (http://localhost/gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:65:98)
    at If (http://localhost/gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:82:141)
    at v (http://localhost/gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:84:389)
    at http://localhost/gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:88:328
    at rd (http://localhost/gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:91:10)
    at O (http://localhost/gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:90:455)
    at yh (http://localhost/gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:105:190)
    at lg (http://localhost/gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)
````
**Configuration:**

Local test on MacOS 10.13.6 with MAMP 5.1, PHP 7.1 and Apache 2.2.34

**Comment by youknowriad** [comment]
Mmm! thanks for the notice, Probably a deprecated component. I'll try to update the plugin as soon as I can.
